# Update these SMTP settings before starting the stack.
global:
  resolve_timeout: 5m
  smtp_smarthost: "smtp.gmail.com:587"
  smtp_from: "udbhav44@gmail.com"
  smtp_auth_username: "udbhav44@gmail.com"
  smtp_auth_password: "hsbiadfwqulrqyzj"
  smtp_require_tls: true

route:
  receiver: email
  group_by: [alertname, instance]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: email
    email_configs:
      - to: "udbhav44@gmail.com"
        send_resolved: true
